spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  cache:
    type: redis
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: error
#    org.hibernate: debug
#    org.hibernate.SQL: debug